site_name: Open Wiki
site_description: Wiki colaborativa de estudiantes para estudiantes, hechas por Open Source eUC

repo_url: https://github.com/open-source-uc/open-wiki
edit_uri: edit/main/docs/

nav:
  - Inicio: index.md
  - Tecnologías:
      - Index: Tecnologías/index.md
      - Herramientas:
          - Visual Studio Code: Tecnologías/Herramientas/vscode.md
          - Google Colab: Tecnologías/Herramientas/google_colab.md
      - Python:
            - Index: Tecnologías/python/index.md
            - Configuraciones: Tecnologías/python/configuraciones.md
      - C:
            - Index: Tecnologías/c/index.md
            - Configuraciones: Tecnologías/c/configuraciones.md
      - html:
            - Index: Tecnologías/html/index.md
            - Configuraciones: Tecnologías/html/configuraciones.md
      - JavaScript:
            - Index: Tecnologías/javascript/index.md
            - Configuraciones: Tecnologías/javascript/configuraciones.md
      - css:
            - Index: Tecnologías/css/index.md
            - Configuraciones: Tecnologías/css/configuraciones.md
      - php:
            - Index: Tecnologías/php/index.md
            - Configuraciones: Tecnologías/php/configuraciones.md
      - ruby:
            - Index: Tecnologías/ruby/index.md
            - Configuraciones: Tecnologías/ruby/configuraciones.md
  - Cursos:
      - Index: Cursos/index.md
      - Compilado de repositorios: Cursos/compilado.md
      - IIC2513 - Tecnologías y Aplicaciones Web:
          - Index: Cursos/web/index.md
          - Resumen: Cursos/web/resumen.md
      - IIC2133 - Estructuras de Datos y Algoritmos:
          - Index: Cursos/edd/index.md
      - IIC1103 - Introduccion a la programación:
          - Index: Cursos/intro_progra/index.md
      - iic2233 - Programación avanzada:
          - Index: Cursos/avanzada/index.md
      - IIC2413 - Bases de Datos:
          - Index: Cursos/bdd/index.md
      - IIC2143 - Ingeniería de Software:
          - Index: Cursos/ing_software/index.md
      - IIC2026 - Visualización de Información:
          - Index: Cursos/visualizacion_informacion/index.md
      - IIC2113 - Diseño Detallado de Software:
          - Index: Cursos/diseño_detallado_software/index.md
      - IIC2283 - Diseño y Análisis de Algoritmos:
          - Index: Cursos/diseño_algoritmos/index.md
      - IIC2333 - Sistemas Operativos y Redes:
          - Index: Cursos/sistemas_operativos/index.md
      - IIC2343 - Arquitectura de Computadores:
          - Index: Cursos/arqui_compu/index.md
      - IIC2553 - Taller de Programación Competitiva II:
          - Index: Cursos/programacion_competitiva/index.md
      - IIC2613 - Inteligencia Artificial:
          - Index: Cursos/inteligencia_artificial/index.md
      - IIC3633 - Sistemas Recomendadores:
          - Index: Cursos/sistemas_recomendadores/index.md
  - Como contribuir: contributing.md

plugins:
  - search
  - git-revision-date-localized:
      locale: es

theme:
  name: material
  language: es
  logo: assets/Open-Wiki-favicon.svg
  favicon: assets/Open-Wiki-favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - search.highlight
    - header.autohide
    - content.code.copy
  palette:
    - scheme: defaultx
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Cambiar a tema oscuro
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Cambiar a tema claro

markdown_extensions:
  - admonition
  - abbr
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://osuc.dev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OpenSource_eUC
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/opensource_euc/
    - icon: fontawesome/brands/github
      link: https://github.com/open-source-uc
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/open-source-euc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VMXCNAvjPW
