site_name: Open Wiki

repo_url: https://github.com/open-source-uc/open-wiki
edit_uri: edit/main/docs/

nav:
  - Inicio: index.md
  - Tecnologías:
      - Herramientas:
          - Visual Studio Code: Tecnologías/Herramientas/vscode.md
          - Google Colab: Tecnologías/Herramientas/google_colab.md
      - Python: Tecnologías/python.md
      - C: Tecnologías/c.md
      - html: Tecnologías/html.md
      - JavaScript: Tecnologías/javascript.md
      - css: Tecnologías/css.md
      - php: Tecnologías/php.md
      - ruby: Tecnologías/ruby.md
  - Cursos:
      - IIC2513 - Tecnologías y Aplicaciones Web:
          - Index: Cursos/web/index.md
          - Resumen: Cursos/web/resumen.md
      - IIC2133 - Estructuras de Datos y Algoritmos:
          - Index: Cursos/edd/index.md
      - IIC1103 - Introduccion a la programación:
          - Index: Cursos/intro_progra/index.md
      - iic2233 - Programación avanzada:
          - Index: Cursos/avanzada/index.md
  - Como contribuir: contributing.md

plugins:
  - search
  - git-revision-date-localized:
      locale: es

theme:
  name: material
  language: es
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - search.highlight
    - header.autohide
    - content.code.copy
  palette:
    - scheme: defaultx
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Cambiar a tema oscuro
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Cambiar a tema claro

markdown_extensions:
  - admonition
  - abbr
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://osuc.dev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OpenSource_eUC
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/opensource_euc/
    - icon: fontawesome/brands/github
      link: https://github.com/open-source-uc
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/open-source-euc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VMXCNAvjPW
